name: Playwright Table Sum

on: [push]

jobs:
  run-playwright:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install playwright

      - name: Run Playwright script (22f3000808@ds.study.iitm.ac.in)
        run: node sum_tables.js
